repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.3.0"
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.9.4"]
